name = "lapce-material-icon-theme"
display-name = "Material Icon Theme"
description = "Material icon theme for Lapce"
version = "0.0.0"
author = "nullndr"
repository = "https://github.com/nullndr/lapce-material-icon-theme"
icon = "logo.png"
icon-themes = ["material.toml"]