author       = "nullndr"
description  = "Material icon theme for Lapce"
display-name = "Material Icon Theme"
icon         = "logo.png"
icon-themes  = ["material.toml"]
name         = "lapce-material-icon-theme"
repository   = "https://github.com/nullndr/lapce-material-icon-theme"
version      = "0.0.2"
